add templating to newscript

diff --git a/scripts/newscript b/scripts/newscript
--- a/scripts/newscript
+++ b/scripts/newscript
@@ -1,5 +1,34 @@
 #!/bin/sh
-[ -z "$1" ] && echo 'Usage: newscript "script_name"' && exit
-[ ! -f "$dotfiles/scripts/$1" ] && echo "#!/bin/sh"  > "$dotfiles/scripts/$1" && chmod +x "$dotfiles/scripts/$1" && vim "$dotfiles/scripts/$1" && $dotfiles/helper_scripts/custom_bin_scripts.sh || vim "$dotfiles/scripts/$1"
 
+[ -z "$dotfiles" ] && echo "Error: \$dotfiles is not defined" && exit 1
 
+template=""
+script_name=""
+
+while [ $# -gt 0 ]; do
+    case "$1" in
+        --template)
+            template="$2"
+            shift 2
+            ;;
+        *)
+            script_name="$1"
+            shift
+            ;;
+    esac
+done
+
+[ -z "$script_name" ] && echo 'Usage: newscript [--template <file>] "script_name"' && exit
+
+if [ ! -f "$dotfiles/scripts/$script_name" ]; then
+    if [ -n "$template" ] && [ -f "$template" ]; then
+        cp "$template" "$dotfiles/scripts/$script_name"
+    else
+        echo "#!/bin/sh" > "$dotfiles/scripts/$script_name"
+    fi
+    chmod +x "$dotfiles/scripts/$script_name"
+    vim "$dotfiles/scripts/$script_name"
+    "$dotfiles/helper_scripts/custom_bin_scripts.sh"
+else
+    vim "$dotfiles/scripts/$script_name"
+fi
