shutil: add shutil script, update scripts/ to use it

diff --git a/scripts/passmenu b/scripts/passmenu
--- a/scripts/passmenu
+++ b/scripts/passmenu
@@ -1,24 +1,20 @@
 #!/usr/bin/env bash
 shopt -s nullglob globstar
 
+. "${XDG_CONFIG_HOME:-$HOME/.config}/sh/shutil.sh"
+
 typeit=0
 if [[ $1 == "--type" ]]; then
     typeit=1
     shift
 fi
 
-if [[ -n $WAYLAND_DISPLAY ]]; then
-    dmenu=dmenu-wl
-    xdotool="ydotool type --file -"
-    display="WL"
-elif [[ -n $DISPLAY ]]; then
-    dmenu=dmenu
-    xdotool="xdotool type --clearmodifiers --file -"
-    display="X11"
-else
-    echo "Error: No Wayland or X11 display detected" >&2
-    exit 1
-fi
+dmenu=$(get_dmenu)
+case $(display_kind) in
+    wl) xdotool="ydotool type --file -"; display="WL" ;;
+    x11) xdotool="xdotool type --clearmodifiers --file -"; display="X11" ;;
+    tty) echo "Error: No Wayland or X11 display detected" >&2; exit 1 ;;
+esac
 
 prefix=${PASSWORD_STORE_DIR-~/.password-store}
 password_files=( "$prefix"/**/*.gpg )
